# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"\x1f\n\x0fSendDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\rSendDataReply\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\x04\x44\x61ta\x12.\n\x08SendData\x12\x10.SendDataRequest\x1a\x0e.SendDataReply\"\x00\x62\x06proto3'
)




_SENDDATAREQUEST = _descriptor.Descriptor(
  name='SendDataRequest',
  full_name='SendDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SendDataRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=48,
)


_SENDDATAREPLY = _descriptor.Descriptor(
  name='SendDataReply',
  full_name='SendDataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SendDataReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['SendDataRequest'] = _SENDDATAREQUEST
DESCRIPTOR.message_types_by_name['SendDataReply'] = _SENDDATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendDataRequest = _reflection.GeneratedProtocolMessageType('SendDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDDATAREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:SendDataRequest)
  })
_sym_db.RegisterMessage(SendDataRequest)

SendDataReply = _reflection.GeneratedProtocolMessageType('SendDataReply', (_message.Message,), {
  'DESCRIPTOR' : _SENDDATAREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:SendDataReply)
  })
_sym_db.RegisterMessage(SendDataReply)



_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='Data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=84,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='Data.SendData',
    index=0,
    containing_service=None,
    input_type=_SENDDATAREQUEST,
    output_type=_SENDDATAREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
